In [4]:
import torch

In [5]:
torch.cuda.is_available() 

True

In [6]:
import torchvision
from torch.utils import data
from torchvision import transforms

In [7]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

In [8]:
x + y

tensor([5.])

In [9]:
x * y

tensor([6.])

In [10]:
x / y

tensor([1.5000])

In [11]:
x ** y

tensor([9.])

In [12]:
 x = torch.arange(4)

In [13]:
x

tensor([0, 1, 2, 3])

In [14]:
x[2]

tensor(2)

In [15]:
len(x)

4

In [16]:
x.shape

torch.Size([4])

In [17]:
A = torch.arange(20).reshape(5,4)

In [18]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [19]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [20]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])

In [21]:
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [22]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [23]:
x = torch.arange(24).reshape(2,3,4)

In [24]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [25]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)

In [26]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [27]:
B = A.clone() # 通过分配新内存，将A的一个副本分配给B

In [28]:
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [29]:
A * B #两个矩阵按元素乘法 

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [30]:
a = 2
a + A

tensor([[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]])

In [31]:
x = torch.arange(4,dtype = torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [45]:
A = torch.arange(40,dtype = torch.float32).reshape(2,5,4)

In [40]:
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [34]:
A.sum()

tensor(780)

In [36]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [37]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [38]:
A_sum_axis2 = A.sum(axis=2)
A_sum_axis2, A_sum_axis2.shape

(tensor([[  6,  22,  38,  54,  70],
         [ 86, 102, 118, 134, 150]]),
 torch.Size([2, 5]))

In [47]:
A_sum_axis3 = A.sum(axis=[0,1])
A_sum_axis3, A_sum_axis3.shape

(tensor([180., 190., 200., 210.]), torch.Size([4]))

In [48]:
A_sum_axis3.mean()

tensor(195.)

In [49]:
A_sum_axis3.mean(axis=0)

tensor(195.)

In [59]:
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [55]:
sum_A = A.sum(axis =0 )
sum_A,sum_A.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [56]:
sum_A = A.sum(axis =0 ,keepdims = True)
sum_A,sum_A.shape

(tensor([[[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]),
 torch.Size([1, 5, 4]))

In [57]:
A / sum_A

tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
         [0.1429, 0.1667, 0.1875, 0.2059],
         [0.2222, 0.2368, 0.2500, 0.2619],
         [0.2727, 0.2826, 0.2917, 0.3000],
         [0.3077, 0.3148, 0.3214, 0.3276]],

        [[1.0000, 0.9545, 0.9167, 0.8846],
         [0.8571, 0.8333, 0.8125, 0.7941],
         [0.7778, 0.7632, 0.7500, 0.7381],
         [0.7273, 0.7174, 0.7083, 0.7000],
         [0.6923, 0.6852, 0.6786, 0.6724]]])

In [60]:
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [61]:
A.sum(axis=0)

tensor([[20., 22., 24., 26.],
        [28., 30., 32., 34.],
        [36., 38., 40., 42.],
        [44., 46., 48., 50.],
        [52., 54., 56., 58.]])

In [64]:
A.cumsum(axis=2)

tensor([[[  0.,   1.,   3.,   6.],
         [  4.,   9.,  15.,  22.],
         [  8.,  17.,  27.,  38.],
         [ 12.,  25.,  39.,  54.],
         [ 16.,  33.,  51.,  70.]],

        [[ 20.,  41.,  63.,  86.],
         [ 24.,  49.,  75., 102.],
         [ 28.,  57.,  87., 118.],
         [ 32.,  65.,  99., 134.],
         [ 36.,  73., 111., 150.]]])

In [72]:
x =torch.arange(4)
y = torch.ones(4,dtype= int)
x,y , torch.dot(x,y)# 点积是相同位置的按元素乘积的和

(tensor([0, 1, 2, 3]), tensor([1, 1, 1, 1]), tensor(6))

In [73]:
torch.sum(x*y) #等价于按元素乘法，然后进行求和来表示两个响亮的点积

tensor(6)

In [85]:
A.shape

torch.Size([2, 5, 4])

In [86]:
B = torch.ones([4,5],dtype= int)

In [87]:
B

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

RuntimeError: expected scalar type Float but found Long