In [1]:
import torch

In [2]:
x = torch.arange(4.0)

In [3]:
x

tensor([0., 1., 2., 3.])

在计算y 关于x 的梯度之前，我们需要一个地方来存储梯度

In [4]:
x.requires_grad_(True) # 等价于 x =  torch.arange(4.0, requires_grad=True)
x.grad  # 可以访问梯度值 默认值是none

现在让我们计算y

In [6]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

通过调用反向传播函数来计算y关于x每个分量的梯度

In [7]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

现在计算x的另一个函数

In [8]:
x.grad.zero_() # 在默认情况下，pytorch会累积梯度，我们需要清楚之前的值
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [9]:
# 通常情况是对标量求导，而不是对向量或者矩阵求导
x.grad.zero_()
y = x * x
y.sum().backward() # backward代价较大，只有求导时才能使用backward
x.grad

tensor([0., 2., 4., 6.])

将某些计算移动到记录的计算图之外

In [10]:
x.grad.zero_()
y = x * x
u = y.detach()  # u视为常数，与x无关，但值大小为x^2
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])